export enum AUTH_PROVIDER {
  WORKOS = "WORKOS",
  SUPABASE = "SUPABASE",
}

export enum SOCIAL_OAUTH_METHOD {
  GOOGLE = "GOOGLE",
  LINKEDIN = "LINKEDIN",
  MICROSOFT = "MICROSOFT",
  APPLE = "APPLE",
  GITHUB = "GITHUB",
}
