export enum PAYMENT_STATUS {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PENDING_REFUND = "PENDING_REFUND",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  FULLY_REFUNDED = "FULLY_REFUNDED",
}

export enum REFUND_STATUS {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  FULLY_REFUNDED = "FULLY_REFUNDED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
}
