// This file contains constant error codes used throughout the application.
// This codes will be used to identify specific error scenarios on the client side.
// Any changes to this file should be reflected in the client application as well.

export const ERROR_CODES = {
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_OTP: "INVALID_OTP",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  PASSWORD_EXPIRED: "PASSWORD_EXPIRED",
  PASSWORD_EXPIRING_SOON: "PASSWORD_EXPIRING_SOON",
  PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  PASSWORD_REUSED: "PASSWORD_REUSED",
  MFA_REQUIRED: "MFA_REQUIRED",
  TOO_MANY_CONCURRENT_QUERIES: "TOO_MANY_CONCURRENT_QUERIES",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  VERIFY_ROW_LIMIT_EXCEEDED: "VERIFY_ROW_LIMIT_EXCEEDED",
  VERIFY_RETENTION_SWEEP_ACTIVE: "VERIFY_RETENTION_SWEEP_ACTIVE",
} as const;

export type TErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
