import mongoose from "mongoose";

import { auditPlugin } from "@/db/plugins/audit/audit.plugin";

const ObjectId = mongoose.Schema.Types.ObjectId;

export interface IVendor {
  _id: mongoose.Types.ObjectId;
  userRef: mongoose.Types.ObjectId;
  companyRef: mongoose.Types.ObjectId;
  stripeAccountId: string;
}

export interface IVendorDocument extends IVendor, mongoose.Document {
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------
// This schema is part of `stripe connect` flow
// ---------------------------------------------
export const VendorSchema = new mongoose.Schema<IVendorDocument>(
  {
    userRef: {
      type: ObjectId,
      ref: "User",
      required: true,
    },
    companyRef: {
      type: ObjectId,
      required: true,
      ref: "Company",
    },
    // Unique identifier for the connected Stripe account of the vendor.
    // This ID is generated by Stripe when a vendor successfully onboards to Stripe Connect.
    stripeAccountId: {
      type: String,
      required: true,
    },
  },
  { timestamps: true },
);

VendorSchema.plugin(auditPlugin, {
  model: "vendor",
  labelField: "stripeAccountId",
});

export const StripeConnectVendor = mongoose.model<IVendorDocument>(
  "StripeConnectVendor",
  VendorSchema,
);
