export const SUBSCRIPTION_MESSAGES = {
  FETCHED_SUCCESS: "Subscription plans fetched successfully.",
  FETCHED_ONE_SUCCESS: "Subscription plan fetched successfully.",
  USER_PLANS_SUCCESS: "User plans fetched successfully.",
  CUSTOMER_CREATED: "Stripe customer created successfully.",
  SUBSCRIPTION_CREATED: "Subscription created successfully.",
  SUBSCRIPTION_CANCELLED: "Subscription cancelled successfully.",
  SUBSCRIPTION_CHANGED: "Subscription changed successfully.",
  UPGRADED_FROM_FREE: "Successfully upgraded from free plan.",
  ALREADY_SUBSCRIBED: "You are already subscribed to this plan!",
  SUBSCRIPTION_PAUSED: "Subscription paused successfully.",
  SUBSCRIPTION_RESUMED: "Subscription resumed successfully.",
  NO_ACTIVE_SUBSCRIPTION: "No active subscription found.",
  ALREADY_PAUSED: "Subscription is already paused.",
  NOT_PAUSED: "Subscription is not paused.",
  CANCELLATION_PENDING: "Subscription is already scheduled for cancellation.",
  RESUME_BEFORE_CHANGE: "Resume your subscription before changing plans.",
  USERS_FETCHED_SUCCESS: "Subscribed users fetched successfully.",
} as const;
